-- CREA UNA BASE DE DATOS EN phpMyAdmin QUE SE LLAME: "tasks"

-- EJECUTA LAS CONSULTAS SOBRE LA BASE DE DATOS

CREATE DATABASE IF NOT EXISTS ToDoDatabase;
USE ToDoDatabase;
CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  username VARCHAR(50) NOT NULL,
  pass VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS todos (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT,
  task VARCHAR(255),
  state VARCHAR(255),
  fecha DATE NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);